name: tests

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '2.3.0'
          - '2.4.0'
          - '2.5.0'
          - '2.6.0'
          - '2.7.0'
          - '3.0.0'
          - '3.1.0'
          - '3.2.0'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
    - uses: codecov/codecov-action@v3
      if: matrix.ruby == '3.2.0'
